### ISSUE TITLE
CSV error when loading table for opensafely/hidradenitis-suppurativa-dermatology/2020-07-29-draft

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#53] opened 2020-07-29 15:55 UTC
Logs:

```
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]: Internal Server Error: /codelist/opensafely/hidradenitis-suppurativa-dermatology/2020-07-29-draft/
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]: Traceback (most recent call last):
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:   File "/var/www/opencodelists/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:     response = get_response(request)
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:   File "/var/www/opencodelists/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:     response = self.process_exception_by_middleware(e, request)
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:   File "/var/www/opencodelists/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:   File "/var/www/opencodelists/codelists/views.py", line 112, in version
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:     headers, *rows = clv.table
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:   File "/var/www/opencodelists/venv/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:     res = instance.__dict__[self.name] = self.func(instance)
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:   File "/var/www/opencodelists/codelists/models.py", line 91, in table
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]:     return list(csv.reader(StringIO(self.csv_data)))
Jul 29 16:52:46 smallweb1.ebmdatalab.net app.opencodelists.web[14218]: _csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
```

**Comment by ghickman** [comment] 2020-09-01 15:19
[Sentry](https://sentry.io/organizations/ebm-datalab/issues/1832009371/)

**Comment by rebkwok** [comment] 2022-12-01 16:54
Closing as can't reproduce and the referenced codelist doesn't exist anymore (the closest is https://www.opencodelists.org/codelist/opensafely/hidradenitis-suppurativa/2020-08-03/, which loads without problems)

**Closed by rebkwok** 2022-12-01 16:54 UTC
